import = [
    "~/.config/alacritty/colors/kanagawa.toml"
    # "~/.config/alacritty/colors/catppuccin-macchiato.toml"
]
shell = "fish"

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 0.95
blur = true

[font]
normal      = { family = "MonoLisa", style = "Book" }
size    = 20
