import = [
    "~/.config/alacritty/colors/gruvbox_dark_hard.toml"
    # "~/.config/alacritty/colors/catppuccin-macchiato.toml"
]
shell = "/opt/homebrew/bin/fish"

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
opacity = 0.95
blur = true
normal      = { family = "MonoLisa", style = "Book" }
# normal      = { family = "JetBrains Mono", style = "Regular" }
# bold        = { family = "Monolisa", style = "Bold" }
# italic      = { family = "Monolisa", style = "Italic" }
# bold_italic = { family = "Monolisa", style = "Bold Italic" }
size        = 17
