import = [
    "~/.config/alacritty/colors/kanagawa.toml"
    # "~/.config/alacritty/colors/catppuccin-macchiato.toml"
]
shell = "fish"

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 0.95
blur = true

[font]
normal      = { family = "MonoLisa", style = "Book" }
# normal      = { family = "JetBrains Mono", style = "Regular" }
# bold        = { family = "Monolisa", style = "Bold" }
# italic      = { family = "Monolisa", style = "Italic" }
# bold_italic = { family = "Monolisa", style = "Bold Italic" }
size        = 17
