import = [
    "~/.config/alacritty/colors/gruvbox_dark_hard.toml"

    # "~/.config/alacritty/colors/kanagawa.toml"
    # "~/.config/alacritty/colors/catppuccin-macchiato.toml"
]
shell = "fish"

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 1
blur = true

[font]
normal      = { family = "MonoLisa", style = "Light" }
italic      = { family = "MonoLisa", style = "Light Italic" }
bold        = { family = "MonoLisa", style = "Regular" }
size        = 20
