[[language]]
name = "btor2"
scope = "source.btor2"
injection-regex = "btor2"
file-types = [ "btor2" ]
# comment-token = ";"
# indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "btor2"
source.path = "/Users/nadirfejzic/Developer/tree-sitter-btor2"

[[language]]
name = "rust"
scope = "source.rs"
rulers = [ 101 ]
file-types = [ "rs" ]
