# Author : Jakub Bartodziej <kubabartodziej@gmail.com>
# The theme uses the gruvbox dark palette with standard contrast: github.com/morhetz/gruvbox

inherits = "gruvbox_dark_hard"

"ui.selection" = { bg = "bg1" }
"ui.selection.primary" = { bg = "bg2" }
"ui.cursor" = { bg = "bg2" }
"ui.cursor.primary" = { bg = "bg4" }
"ui.cursor.match" = { bg = "bg2" }

"diagnostic.error" = { underline = { color = "red0", style = "curl"} }

[palette]
bg0 = "#1d2021" # main background
