[plugins]
smart-splits = { url = "https://github.com/mrjones2014/smart-splits.nvim", tag = "v2.0.3"}
tmux-ssh-split = "https://github.com/pschmitt/tmux-ssh-split"
tmux-fingers = "https://github.com/Morantron/tmux-fingers"
