[metadata]
name = "gruvbox-dark-hard"
author = "Nadir Fejzić"

[colors]

ansi = [
    "#3c3836",
    "#cc241d",
    "#98971a",
    "#d79921",
    "#458588",
    "#b16286",
    "#689d6a",
    "#504945",
]

brights = [
    "#665c54",
    "#fb4934",
    "#b8bb26",
    "#fabd2f",
    "#83a598",
    "#d3869b",
    "#8ec07c",
    "#ebdbb2",
]

background = "#1d2021"
foreground = "#ebdbb2"

cursor_bg = "#ebdbb2"
cursor_border = "#ebdbb2"
cursor_fg = "#1d2021"

selection_bg = "#504945" # ansi[8],
selection_fg = "#ebdbb2" # brights[8]

scrollbar_thumb = "#3c3836" # ansi[1]
split = "#3c3836"           # ansi[1]
visual_bell = "#3c3836"     # ansi[1]

[colors.tab_bar]
background = "#3c3836"              # ansi[1]
inactive_tab_edge = "#3c3836"       # ansi[1]
inactive_tab_edge_hover = "#3c3836" # ansi[1]

[colors.tab_bar.active_tab]
bg_color = "#3c3836" # ansi[1]
fg_color = "#fabd2f" # brights[4]

[colors.tab_bar.inactive_tab]
bg_color = "#3c3836" # ansi[1]
fg_color = "#ebdbb2" # brights[8] / foreground
